node {
   def commit_id

   environment { 
     imagename  = "mysmallimage"
     //dockerImage =''
   }
   stage('Preparation') {
     checkout scm
     sh "git rev-parse --short HEAD > .git/commit-id"                        
     commit_id = readFile('.git/commit-id').trim()
   }
   stage('test') {
     nodejs(nodeJSInstallationName: 'nodejs') {
       sh 'npm install --only=dev'
       sh 'npm test'
     }
   }
   stage('docker build') {
         //def dockerImage = docker.build imagename
         def app = docker.build("mlysenko/ml:${env.BUILD_ID}", '.')
   }
   stage('docker push') {
       docker.withRegistry('https://index.docker.io/v2/', 'dockerhub-creds') {
       //def app = docker.build("mlysenko/ml:${env.BUILD_ID}", '.')
          app.push()
          //sh "docker build -t mlysenko/ml . "
          //withDockerRegistry([ credentialsId: "dockerhub-creds", url: ""]){
          //sh "docker push mlysenko/ml:${env.BUILD_TAG} "
          //app.push("$BUILD_NUMBER")
          //app.push('latest')
       }
     }
}

