node {
   def commit_id
   stage('Preparation') {
     checkout scm
     sh "git rev-parse --short HEAD > .git/commit-id"                        
     commit_id = readFile('.git/commit-id').trim()
   }
   stage('test') {
     nodejs(nodeJSInstallationName: 'nodejs') {
       sh 'npm install --only=dev'
       sh 'npm test'
     }
   }
   stage('docker build/push') {
     //docker.withRegistry('https://index.docker.io/v2/', 'dockerhub-creds') {
     //  def app = docker.build("mlysenko/ml:${commit_id}", '.').push()
        sh "docker build -t mlysenko/ml . "
       withDockerRegistry([ credentialsId: "dockerhub-creds", url: ""]){
         sh "docker push --all-tags mlysenko/ml "
       }
     }
}

